dist: trusty
language: cpp
addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libopenblas-dev
      - libboost-all-dev
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - wget http://dlib.net/files/dlib-19.16.tar.bz2
  - mkdir dlib
  - tar xvf dlib-19.15.tar.bz2 -C dlib --strip-components=1
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T realty-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -urfrolov:$BINTRAY_API_KEY "https://api.bintray.com/content/rfrolov/otus/otus_homework_16/$TRAVIS_BUILD_NUMBER/realty-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"